# Generated by Django 5.2.7 on 2025-11-18 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'A Fazer'), (2, 'Fazendo'), (3, 'Feito')], default=1)),
                ('etiqueta', models.PositiveSmallIntegerField(choices=[(1, 'Urgente'), (2, 'Importante'), (3, 'Normal'), (4, 'Baixa Prioridade'), (5, 'Opcional')], default=3)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='projeto.projeto')),
            ],
        ),
    ]
